# Generated by Django 3.1.3 on 2020-11-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='Modular',
            new_name='modular',
        ),
        migrations.AlterField(
            model_name='run',
            name='createtime',
            field=models.DateTimeField(unique=True, verbose_name='创建时间'),
        ),
    ]
