# Generated by Django 3.1.3 on 2020-11-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='createtime',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='run',
            name='modular',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.modular', verbose_name='用户执行id'),
        ),
        migrations.AlterField(
            model_name='run',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='用户执行id'),
        ),
    ]
