# Generated by Django 3.1.3 on 2020-11-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api',
            old_name='case_careatetime',
            new_name='case_createtime',
        ),
    ]
