# Generated by Django 3.1.3 on 2020-11-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201125_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='runsave',
            field=models.JSONField(max_length=4500, null=True, verbose_name='运行结果链接'),
        ),
    ]
