# Generated by Django 3.1.3 on 2020-11-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201111_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='run_url',
            field=models.CharField(max_length=45, null=True, verbose_name='运行结果链接'),
        ),
    ]
