# Generated by Django 3.1.3 on 2020-11-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201111_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursor',
            name='user_value',
            field=models.CharField(max_length=4500, verbose_name='保留字段值'),
        ),
        migrations.AlterField(
            model_name='cursor',
            name='usr_key',
            field=models.CharField(max_length=4500, verbose_name='保留字段名'),
        ),
    ]
