# Generated by Django 3.1.3 on 2020-11-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201112_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='casename',
            field=models.CharField(max_length=45, null=True, verbose_name='用例名称'),
        ),
    ]
