# Generated by Django 3.1.3 on 2020-11-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201112_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modular',
            name='platform',
            field=models.CharField(max_length=45, null=True, verbose_name='平台'),
        ),
    ]
