# Generated by Django 3.1.3 on 2020-11-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_modular_api_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modular',
            name='api_id',
        ),
        migrations.AddField(
            model_name='run',
            name='api_id',
            field=models.CharField(max_length=45, null=True, verbose_name='执行id'),
        ),
    ]
